@host = localhost
@port = 3000
@apiversion = api/v1

### Recuperar Um Categoria por ID
GET http://{{host}}:{{port}}/{{apiversion}}/categorias/9d9cffca-4a0e-4964-b115-ef2808253ed5


### Recuperar Todas as Categorias
GET http://{{host}}:{{port}}/{{apiversion}}/categorias


### Inserir Uma Categoria
POST http://{{host}}:{{port}}/{{apiversion}}/categorias
Content-type: application/json

{
    "nome":"Sala de Estar"
}